Musicplayer
pranjay-poddar/Dev-Geeks pull request #1289
Opened 2023-05-23 11:18 UTC by SimranLahrani842

#1254 
python project (music player)

Close #1254

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

2023-05-23 11:34 UTC, SimranLahrani842 commented
@pranjay-poddar added music player and updates the readme.md ,kindly review my PR.

2023-05-23 11:50 UTC, SimranLahrani842 commented
@pranjay-poddar added music player and updated the readme.md rows and added project title to it, kindly review my PR.

2023-05-25 19:41 UTC, pranjay-poddar approved these changes

2023-05-25 19:41 UTC, pranjay-poddar commented
Resolve conflicts

2023-05-25 19:41 UTC, pranjay-poddar requested changes
Resolve conflicts

2023-05-25 19:51 UTC, SimranLahrani842 commented
> Resolve conflicts

Done sir ,add label and gssoc and kindly review it @pranjay-poddar

2023-06-07 07:43 UTC, pranjay-poddar approved these changes

2023-06-07 07:44 UTC, pranjay-poddar requested changes
Resolve conflicts

2023-06-25 18:08 UTC, SimranLahrani842 commented
> Resolve conflicts

Please merge sir @pranjay-poddar

2023-07-04 16:18 UTC, MohitGupta121 approved these changes

2023-07-04 16:19 UTC, MohitGupta121 requested changes

2023-07-04 16:19 UTC, MohitGupta121 commented on Python Projects/Music Player/images.jpeg
@SimranLahrani842 please not upload images, gif in your PR. Upload them in somewhere at cloud and use that image/gif links into your project to load them.

2023-07-05 04:22 UTC, SimranLahrani842 commented on Python Projects/Music Player/images.jpeg
> @SimranLahrani842 please not upload images, gif in your PR. Upload them in somewhere at cloud and use that image/gif links into your project to load them.

How to do that previously and in all other projects we have been doing the same uploading in our folder itself...

2023-07-05 13:50 UTC, MohitGupta121 commented on Python Projects/Music Player/images.jpeg
You habe to use image link not directly image path it's as simple as you add image path

2023-07-06 13:37 UTC, SimranLahrani842 commented on Python Projects/Music Player/images.jpeg
> You habe to use image link not directly image path it's as simple as you add image path

next time i ll upload the link,for this PR please merge as its been almost month now!! @pranjay-poddar and @MohitGupta121

2023-07-06 19:13 UTC, MohitGupta121 commented
@SimranLahrani842 I think you can make new PR for this I closing this as @pranjay-poddar  is busy and for merging his review is needed.

2023-07-06 19:15 UTC, SimranLahrani842 commented
> @SimranLahrani842 I think you can make new PR for this I closing this as @pranjay-poddar is busy and for merging his review is needed.

Bro how can u close the pr  it was done 1.5 months ago...I did same in other repos too.. @MohitGupta121 @pranjay-poddar

2023-07-06 19:18 UTC, pranjay-poddar approved these changes

2023-07-06 19:34 UTC, pranjay-poddar approved these changes

2023-07-06 19:34 UTC, pranjay-poddar commented
Resolve conflicts

2023-07-06 19:40 UTC, SimranLahrani842 commented
> Resolve conflicts

Done sir🥰

2023-07-06 20:33 UTC, MohitGupta121 requested changes
@SimranLahrani842 please remove all gif/ images from the PR and upload them in somewhere in cloud and after that use that link of gif, image to load into your project.

2023-07-07 08:35 UTC, closed without merging