Added the responsive tip calculator project
pranjay-poddar/Dev-Geeks pull request #1354
Opened 2023-05-24 12:12 UTC by yagyesh-bobde

# Tip Calculator Project #1352

Close #1352 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy-to-understand `README.md`

2023-06-10 10:42 UTC, MohitGupta121 requested changes
@yagyesh-bobde please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

2023-06-14 06:04 UTC, yagyesh-bobde commented
> @yagyesh-bobde please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

Okay will do!

2023-06-15 19:57 UTC, MohitGupta121 approved these changes

2023-06-15 19:58 UTC, MohitGupta121 commented
Project already present

2023-06-15 19:58 UTC, closed without merging