Requesting to Merge: Improve UI to Birthday Website
pranjay-poddar/Dev-Geeks pull request #1413
Opened 2023-05-25 14:12 UTC by devasyarajguru

# Title and Issue number 

Title: Improve UI to Birthday Website
Issue Number: 1013

Close #1013 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

<img width="960" alt="birthday" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/84851506/0169c179-7be6-40ac-869e-3318b719958a">

2023-05-27 06:28 UTC, devasyarajguru commented
Hey @pranjay-poddar Please review my PR and if it goes well please merge it. Also please add level-2 tag. Thank You!

2023-05-30 06:15 UTC, devasyarajguru commented
@Saurabh-kumar09 Please review my PR and if it goes well please merge it. Also please add level-2 tag. Thank You!

2023-06-10 10:31 UTC, MohitGupta121 requested changes
@devasyarajguru please resolves conflicts to merge this PR

2023-06-14 08:26 UTC, devasyarajguru commented
@MohitGupta121 As per requested changes are made , commit message is - "Merge branch main into devasya23" mentioned above in the conversation. Please check it and merge my PR

2023-06-15 13:46 UTC, MohitGupta121 requested changes
@devasyarajguru  please don't upload directly too much large size files fetch or use them from cloud url such as 1st you upload your video in google drive or directly in Github, after that you get 1 link use that link in your project, not use directly images, videos files.
This increases the whole Dev-Greek project size.
Thanks!

2023-06-15 17:57 UTC, MohitGupta121 requested changes

2023-06-15 17:57 UTC, MohitGupta121 commented on Frontend-Projects/birthday website/balloons.jpg
@devasyarajguru I am saying to use these image files from the cloud or use its link. Don't upload the images in the PR. Fetch them from google drive or any other cloud image link.

2023-06-15 17:57 UTC, MohitGupta121 commented on Frontend-Projects/birthday website/balloons1.jpg
same for this images.

2023-06-21 09:36 UTC, devasyarajguru commented
Hey @MohitGupta121 , I have resolved my conflicts in my VS Code. After that I did commit and try to push the local changes to the repo, but it did'nt work out , I am getting errors which I tried to search solutions for it but did'nt solve any. Please help me with it, I am posting screenshot of errors below. 

### **`No. 1 `**- <img width="932" alt="1" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/84851506/101ff36e-7179-41f6-9e06-c9e889d5aff3">

### **`No.2`**
<img width="763" alt="2" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/84851506/df0a0ff1-bfe1-43a1-9485-98867efd39db">

### **`No.3`**
<img width="557" alt="3" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/84851506/37892dc6-e2cd-456a-83ee-683b6bc0b7f1">


### **`No.4`**
<img width="598" alt="4" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/84851506/382b544e-655c-4823-ad5e-fe834c760791">

### **`No.5`**
<img width="757" alt="5" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/84851506/6342b273-eb4b-469f-8c72-a1d5c7cba66e">

### **`No.6`**
<img width="618" alt="8" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/84851506/22cd140b-4eee-4a03-8bef-500813cbbba1">

2023-06-22 02:48 UTC, MohitGupta121 commented
@devasyarajguru you also have to update your branch with main upstream branch then this will resolve

2023-06-22 14:01 UTC, closed without merging