added climate api project in Node-JS project folder
pranjay-poddar/Dev-Geeks pull request #1567
Opened 2023-05-29 12:13 UTC by RJ025

# climate API Issue number : 1451

Close #1451 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas

2023-06-05 18:22 UTC, RJ025 commented
which files are not committed properly

2023-06-15 20:16 UTC, MohitGupta121 requested changes

2023-06-15 20:16 UTC, MohitGupta121 commented on Node-JS Projects/climate-api
@RJ025 You need to commit whole project files, in files change see nothing here.

2023-07-04 16:25 UTC, MohitGupta121 commented
Inactive

2023-07-04 16:25 UTC, closed without merging