Added To-Do list in Js-Project-
pranjay-poddar/Dev-Geeks pull request #1674
Opened 2023-06-02 00:16 UTC by Biswajit-Behera

# Title and Issue number 
To Do list Web Application and issue:- #1423

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

2023-06-02 22:13 UTC, pranjay-poddar requested changes
Change the issue number

2023-06-03 03:54 UTC, Biswajit-Behera commented
> Change the issue number

I think I have mentioned the correct issue number as I had created for To Do web Application issue number:-#1432

2023-07-04 16:29 UTC, MohitGupta121 requested changes

2023-07-04 16:29 UTC, MohitGupta121 commented on Js-Projects/To DO List/Screenshot 2023-06-01 at 12.21.23.png
@Biswajit-Behera please remove all the images from your PR and use them through cloud link. Upload somewhere the images and use them from that link.

2023-08-06 05:24 UTC, closed without merging