Update style.css
pranjay-poddar/Dev-Geeks pull request #1686
Opened 2023-06-02 11:34 UTC by Mansi8874

Done the changes according to issue number pranjay-poddar #1668

# Title and Issue number 
Added some Animations on footer_new and the issue number is #1668

Close #1688

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

2023-06-05 18:01 UTC, pranjay-poddar reviewed
Mention issue number in correct PR format

2023-06-05 18:02 UTC, pranjay-poddar requested changes
Follow instructions in temple

2023-07-04 16:29 UTC, MohitGupta121 approved these changes

2023-07-04 16:30 UTC, MohitGupta121 commented
@pranjay-poddar  please merge this as now changes approved.

2023-07-06 16:52 UTC, closed without merging