<add your message here>
pranjay-poddar/Dev-Geeks pull request #1727
Opened 2023-06-03 10:23 UTC by yash8917

# Title and Issue number 

Close #<issue_no>

# Checklist:

- [] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`
- [] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

2023-06-09 16:39 UTC, MohitGupta121 requested changes
@yash8917 please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

2023-06-10 13:08 UTC, yash8917 commented
Attached a Screen Recording of the Changes.
Repo Link ->https://github.com/yash8917/Dice_Game
Live Link ->https://yash8917.github.io/Dice_Game/
https://github.com/pranjay-poddar/Dev-Geeks/assets/90241440/797314d5-7a8c-4153-8bd6-817a97434485

2023-06-10 15:51 UTC, MohitGupta121 approved these changes

2023-06-10 15:51 UTC, merged

2023-06-15 08:21 UTC, yash8917 commented
Hello sir , the changes i have made in that i think it should be a label as lvl2 .if you promote it to lvl2 issues it could be justify my hard work.