Added Yoga project to frontend
pranjay-poddar/Dev-Geeks pull request #1815
Opened 2023-06-06 06:50 UTC by sumitkr2000

# Title and Issue number 
Hey @pranjay-poddar I have added the yoga project to Frontend. Please review my project n merge it. Thank you!

Close #1055 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

2023-06-07 03:01 UTC, sumitkr2000 commented
Please merge this pr!

2023-06-09 16:29 UTC, MohitGupta121 requested changes
@sumitkr2000 please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

2023-06-11 06:57 UTC, sumitkr2000 commented
[screen-capture.webm](https://github.com/pranjay-poddar/Dev-Geeks/assets/100675296/7575a7b9-a5f8-4fe8-a314-7d81ddeb0ae2)


@MohitGupta121

2023-06-11 10:27 UTC, MohitGupta121 approved these changes

2023-06-11 10:27 UTC, merged