change navbar : Fruit website #1829
pranjay-poddar/Dev-Geeks pull request #1885
Opened 2023-06-07 15:09 UTC by kaurjaskirat

# Title and Issue number 

Close #1829

# Checklist:

- [] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

2023-06-07 16:22 UTC, kaurjaskirat commented
@pranjay-poddar please review.

2023-06-09 15:59 UTC, MohitGupta121 requested changes
@kaurjaskirat please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

2023-06-10 13:47 UTC, kaurjaskirat commented
@MohitGupta121 
Here is the screen recording of the changes.

https://github.com/pranjay-poddar/Dev-Geeks/assets/104628038/fb493fc2-ce4b-4ee1-ba73-4dced5c0f94d

2023-06-10 15:54 UTC, MohitGupta121 approved these changes

2023-06-10 15:54 UTC, merged