Social Media Reference Landing Page Project added [GSSoC'23]
pranjay-poddar/Dev-Geeks pull request #2125
Opened 2023-06-14 07:38 UTC by AnupK1234

# Social Media Reference Landing Page Project #2085 

Close #2085 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

2023-06-15 10:16 UTC, AnupK1234 commented
Hello @pranjay-poddar @MohitGupta121 ,
Kindly review this PR.

2023-06-15 14:06 UTC, MohitGupta121 requested changes
@AnupK1234 please follow this:

1. Please don't upload directly too much large size files fetch or use them from cloud url such as 1st you upload your video in google drive or directly in Github, after that you get 1 link use that link in your project, not use directly images, videos files.
This increases the whole Dev-Greek project size.

2. Add video recording of your project site demonstration.

Thanks!

2023-06-16 11:33 UTC, MohitGupta121 requested changes
@AnupK1234 you are still there please remove images files or other graphic files from PR fetch them from cloud or using link

2023-06-16 19:27 UTC, MohitGupta121 approved these changes

2023-06-16 19:28 UTC, merged