[ADD]: INSURE LANDING PAGE ✨
pranjay-poddar/Dev-Geeks pull request #2165
Opened 2023-06-15 04:00 UTC by 0xabdulkhalid

# Close #2019 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

2023-06-15 04:07 UTC, 0xabdulkhalid commented
Respected @MohitGupta121, @pranjay-poddar please review this PR

2023-06-15 13:57 UTC, MohitGupta121 requested changes
@0xabdulkhalid please don't upload directly too much large size files fetch or use them from cloud url such as 1st you upload your video in google drive or directly in Github, after that you get 1 link use that link in your project, not use directly images, videos files.
This increases the whole Dev-Greek project size.
Thanks!

2023-06-16 14:57 UTC, 0xabdulkhalid commented
Done @MohitGupta121, you can verify this PR now!

2023-06-16 17:38 UTC, MohitGupta121 approved these changes

2023-06-16 17:38 UTC, merged