Added new project #1658
pranjay-poddar/Dev-Geeks pull request #2240
Opened 2023-06-16 16:58 UTC by Jranii

Hello,
As per issue number #1658, I have added a temperature converter project. Kindly review and merge it. 
Along with I have provided a screen recording of the project in the pull request.

https://github.com/pranjay-poddar/Dev-Geeks/assets/102273107/b8ad40eb-b2c8-42b5-9568-161e66daf21c

Close #1658

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

2023-06-17 03:05 UTC, pranjay-poddar approved these changes

2023-06-17 03:06 UTC, pranjay-poddar commented
resolve conflicts

2023-06-17 03:07 UTC, pranjay-poddar requested changes
resolve conflicts

2023-07-04 16:38 UTC, MohitGupta121 commented
@pranjay-poddar, please approved this PR.

2023-08-06 05:24 UTC, closed without merging