Live Analog Clock using JavaScript #2181
pranjay-poddar/Dev-Geeks pull request #2260
Opened 2023-06-16 20:16 UTC by ahanban15

Live Analog Clock using JavaScript #2181

Close #2181 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

2023-06-16 20:22 UTC, ahanban15 commented
@pranjay-poddar and other mentors, I have contributed the required Live Analog clock project using JS under JS-Projects folder. Kindly judge my contribution and please suggest any changes if necessary. Kindly provide the approving review to be able to merge my contribution to DevGeeks for a humble successful contribution under GSSoC'23.

2023-06-16 20:24 UTC, ahanban15 commented
@pranjay-poddar and other mentors, I have contributed the required Live Analog clock project. Kindly judge my contribution and please suggest any changes if necessary. Kindly provide the approving review to be able to merge my contribution to DevGeeks for a humble successful contribution

2023-06-17 01:53 UTC, pranjay-poddar requested changes
Remove.vscode folder committed in root from your commit

2023-06-17 04:11 UTC, ahanban15 commented
Kindly review the new commit made @pranjay-poddar and other mentors. Removed the .vscode folder as suggested.

2023-07-06 21:05 UTC, MohitGupta121 requested changes
@ahanban15 please remove the image from PR and upload it somewhere in cloud and use the link of the image to load the image into your Project.

2023-07-09 17:43 UTC, ahanban15 commented
Issue #2260 
@pranjay-poddar @MohitGupta121 done as suggested, kindly review the PR and merge my contribution to DevGeeks for a humble successful contribution under GSSoC'23.

2023-07-10 17:27 UTC, MohitGupta121 requested changes

2023-07-10 17:27 UTC, MohitGupta121 commented on Js-Projects/Live Analog Clock using JS/clock.jpg
@ahanban15 image is still there

2023-07-10 18:57 UTC, ahanban15 commented on Js-Projects/Live Analog Clock using JS/clock.jpg
Done sir, kindly verify now.

2023-07-11 17:33 UTC, MohitGupta121 commented on .vscode/settings.json
@ahanban15 please not change this file

2023-08-06 05:24 UTC, closed without merging