Car Plate Number Detection
pranjay-poddar/Dev-Geeks pull request #2269
Opened 2023-06-17 06:46 UTC by Shreyg-27

# Title and Issue number 
Car Plate Number Detection #1828 

Close #<issue_no>
Close #1828 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

2023-06-17 06:47 UTC, Shreyg-27 commented
Hi @MohitGupta121! I have added the car plate number detection folder under the ml project folder. It would be great if you could review it. 
Thank you!

2023-06-18 18:49 UTC, MohitGupta121 requested changes
@Shreyg-27 please not upload images in your PR use that images from link that redirect to your images ( you should store that images at anywhere in cloud)

2023-06-22 07:11 UTC, Shreyg-27 commented
Hi @MohitGupta121! 
In the images folder, I have updated the README.md file with the links of all the images. 
These images are uploaded on Imgur.

2023-06-22 18:02 UTC, MohitGupta121 approved these changes

2023-06-22 18:02 UTC, merged