Added responsive and stylish Event Landing Page
pranjay-poddar/Dev-Geeks pull request #2341
Opened 2023-06-18 19:53 UTC by PoulavBhowmick03

# Title and Issue number 
Landing page for an Events website #2323

Close #2323 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/02c186e1-0d38-43b9-ad51-57a99bd33b19

2023-06-18 19:53 UTC, PoulavBhowmick03 commented
@MohitGupta121

2023-06-19 07:46 UTC, MohitGupta121 requested changes
@PoulavBhowmick03 please use images or ny assets through link in your project not upload images, or anything in your PR, that link will redirect to that particular assets/images which store in any cloud.

Also please remove  `.DS_Store` files from your PR.

2023-06-19 14:09 UTC, PoulavBhowmick03 commented
@MohitGupta121 changes done

2023-06-19 15:11 UTC, PoulavBhowmick03 commented
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/81046ccc-208f-4b3a-9b5f-bf3a18af18dc)
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/a26eee17-f5af-440a-a7e8-8dc5088a4615)
@MohitGupta121 But I have already deleted all the images. Check the ss of my commit and the clone repo

2023-06-19 16:13 UTC, MohitGupta121 requested changes
@PoulavBhowmick03 PTAL

2023-06-19 16:13 UTC, MohitGupta121 commented on Frontend-Projects/Events_Landing_Page/assets/css/.DS_Store
Please remove these files from project they are still there use this command to delete all files at once in whole project `find . -name ".DS_Store" -type f -delete`

2023-06-19 17:44 UTC, PoulavBhowmick03 commented
@MohitGupta121 Done. Check

2023-06-20 02:00 UTC, MohitGupta121 requested changes
@PoulavBhowmick03 if your changes only in Frontend-Projects/Events_Landing_Page then why you posting other folders in file changes like TinDog Website, Js-Game etc. Please remove unnecessary things from your PR. Thanks!

2023-06-20 02:42 UTC, PoulavBhowmick03 commented
I am sorry, I dont have any idea on what went wrong. I would close this PR, discard the commits and work on it later @MohitGupta121

2023-06-20 02:42 UTC, closed without merging