Added Envelope Animation
pranjay-poddar/Dev-Geeks pull request #2357
Opened 2023-06-19 11:05 UTC by 5h0ov

# Envelope Animation 
Successfully added the Animation of an Envelope which opens and closes on hover for Issue #1060 

Close #1060 

# Preview:
![envelope](https://github.com/pranjay-poddar/Dev-Geeks/assets/83227649/606f2045-6bde-4a92-8d74-1af780bd7f17)

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

2023-07-04 16:49 UTC, MohitGupta121 requested changes

2023-07-04 16:49 UTC, MohitGupta121 commented on Animations-CSS/Animated Envelope/envelope.gif
@5h0ov  please remove all the gifs from your PR and use them through the cloud link. Upload somewhere the gif and use them from that link.

2023-07-04 17:32 UTC, 5h0ov commented on Animations-CSS/Animated Envelope/envelope.gif
done 👍

2023-07-05 13:39 UTC, MohitGupta121 approved these changes

2023-07-05 13:39 UTC, merged