Added Basic Calculator
pranjay-poddar/Dev-Geeks pull request #2358
Opened 2023-06-19 11:19 UTC by Anshul439

New Project - Basic Calculator [GSSoC'23] #2117

Close #2117 
# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

Please add gssoc label to this one and PR #2016

2023-06-22 18:15 UTC, pranjay-poddar requested changes
Move file to frontend folder

2023-06-22 19:45 UTC, Anshul439 commented
I have moved it already. Please check again

2023-07-04 16:49 UTC, MohitGupta121 approved these changes

2023-07-04 16:50 UTC, MohitGupta121 commented
@pranjay-poddar Please approve this PR.

2023-08-06 05:24 UTC, closed without merging