Back to top link added.🔝
pranjay-poddar/Dev-Geeks pull request #2539
Opened 2023-06-22 13:34 UTC by arcVaishali

# Back to Top Link missing from the Readme #1755 

Back to Top link added🔝

Close #1755 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

2023-07-04 16:54 UTC, MohitGupta121 requested changes

2023-07-04 16:54 UTC, MohitGupta121 commented on .vscode/settings.json
please not change this file

2023-07-04 16:58 UTC, arcVaishali commented on .vscode/settings.json
Okay I will check and revert changes

2023-07-11 14:44 UTC, arcVaishali reviewed
Reverted the changes made in .vscode/settings.json

2023-07-12 20:22 UTC, MohitGupta121 requested changes

2023-07-12 20:22 UTC, MohitGupta121 commented on .vscode/settings.json
@arcVaishali why you remove all content from this , remove the file changes of this file from your PR.

2023-07-13 02:41 UTC, arcVaishali commented on .vscode/settings.json
Okay, I misunderstood. I have to add this file in gitignore folder. I guess then only, changes made to this file will not be a part of this PR?

2023-07-13 03:00 UTC, arcVaishali commented on .vscode/settings.json
I have removed .vscode folder completely

2023-07-13 04:25 UTC, MohitGupta121 approved these changes

2023-07-13 04:26 UTC, merged