Adding Memory card game
pranjay-poddar/Dev-Geeks pull request #2571
Opened 2023-06-23 06:29 UTC by pavitrachavda97

# Title and Issue number 

Memory Card

Close #2110 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

2023-07-04 16:55 UTC, MohitGupta121 requested changes
@pavitrachavda97   please remove all the images or gif from your PR and use them through cloud link. Upload somewhere the images and use them from that link.

2023-07-07 06:32 UTC, pavitrachavda97 commented
@MohitGupta121
Thank you for the feedback! I have made the requested changes by removing the images from the PR. Instead, I have uploaded the images to a cloud storage service and updated the code to use cloud links. I have tested the modified code locally, and the images are loading correctly from the cloud links. The changes have been committed and pushed to the repository. Please review the updated code and let me know if any further adjustments are needed. Thank you!

2023-07-08 03:39 UTC, MohitGupta121 requested changes

2023-07-08 03:39 UTC, MohitGupta121 commented on Js-Games/memoryCard/images/img1.png
no @pavitrachavda97 all images are still there

2023-07-08 04:52 UTC, pavitrachavda97 commented
@MohitGupta121 
I have removed images folder now. Please review the updated code and let me know if any further adjustments are needed. 
Thank you!

2023-07-08 22:05 UTC, MohitGupta121 approved these changes

2023-07-08 22:06 UTC, merged