Added Linkedin Project
pranjay-poddar/Dev-Geeks pull request #2596
Opened 2023-06-23 12:28 UTC by SyedImtiyaz-1

Issue No. #2595 

Hello Project Admin,
I have added the Linkedin Clone {Replica}

### Screenshot -
![Screenshot from 2023-06-23 17-56-53](https://github.com/pranjay-poddar/Dev-Geeks/assets/121503426/871b74b1-0f5e-491b-836f-f21cbcf9b8aa)

### It is ready to Merge 👍🏻

2023-06-24 07:36 UTC, SyedImtiyaz-1 commented
## Hello Project Admin,
Kindly give this a review .

2023-06-24 20:24 UTC, SyedImtiyaz-1 commented
Hello @TusharKesarwani ,
please review this one.

2023-06-27 11:38 UTC, SyedImtiyaz-1 commented
Hello @TusharKesarwani ,
Kindly review this 👍🏻

2023-06-28 15:27 UTC, SyedImtiyaz-1 commented
Please review this. 
@TusharKesarwani , @pranjay-poddar , @Saurabh-kumar09 , @MohitGupta121

2023-06-29 15:27 UTC, SyedImtiyaz-1 commented
Hello @MohitGupta121 ,
I have fixed the directory and added drive imgs files. 
### It is  ready to merge 👍🏻

2023-06-29 15:38 UTC, MohitGupta121 requested changes
@SyedImtiyaz-1 PTAL

2023-06-29 15:47 UTC, SyedImtiyaz-1 commented on Js-Games/Spider_Man_Go/images/knife.png
Okay Got It working on it.

2023-06-30 09:31 UTC, SyedImtiyaz-1 commented
@MohitGupta121 please review this.

2023-06-30 17:16 UTC, SyedImtiyaz-1 commented
@MohitGupta121 ,
Conflict Resolved 👍🏻

2023-06-30 17:16 UTC, MohitGupta121 commented
You said added LinkedIn clone but I saw in your PR it's Spider man game. Make new clean PR.

2023-06-30 17:16 UTC, closed without merging

2023-06-30 17:16 UTC, MohitGupta121 commented
Also use proper PR template.

2023-06-30 17:18 UTC, SyedImtiyaz-1 commented
Sure