Word
pranjay-poddar/Dev-Geeks pull request #2656
Opened 2023-06-25 06:10 UTC by manasi-jain

# Title and Issue number 

Word Scramble Game 

Close #2646

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have created a helpful and easy to understand `README.md`

2023-06-26 07:20 UTC, MohitGupta121 requested changes
@manasi-jain if this only Word Scramble project then why you adding flutter projects also in your PR. Remove all unnecessary folder and codes.

2023-06-27 03:33 UTC, manasi-jain commented
@MohitGupta121 I have made changes to address the feedback provided. Please take a look at the updated code.

2023-06-29 14:09 UTC, MohitGupta121 requested changes
@manasi-jain PTAL, Thanks.

2023-06-29 14:09 UTC, MohitGupta121 commented on Js-Games/WordScramble/background.png
@manasi-jain please use don't upload image in PR use them from Link in your project.

2023-06-29 14:09 UTC, MohitGupta121 commented on Js-Games/WordScramble/word_scramble.gif
@manasi-jain same for this files use the link. Upload these file somewhere and load them through link in your actual project.

2023-08-06 05:24 UTC, closed without merging