added Drum Sound Project
pranjay-poddar/Dev-Geeks pull request #2663
Opened 2023-06-25 09:44 UTC by Nayan808

Hello Project Admin,
### I have added a Spider Man Game which I mention in the issue no. #2660 .

## Screenshot -
![Screenshot from 2023-06-25 15-08-55](https://github.com/pranjay-poddar/Dev-Geeks/assets/107837638/60df6ba0-7a7e-4deb-aae9-983ceee28338)

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### It is super ready to `Merge`

2023-07-04 16:57 UTC, MohitGupta121 requested changes
@Nayan808   please remove all the images or gif from your PR and use them through cloud link. Upload somewhere the images and use them from that link.

2023-07-04 16:57 UTC, MohitGupta121 requested changes

2023-07-04 16:57 UTC, MohitGupta121 commented on Drum-Sounds/.DS_Store
Also remove this file

2023-07-04 17:50 UTC, Nayan808 reviewed
@MohitGupta121 
Edited the Code And Added Images By cloud And Removed files

2023-07-05 13:41 UTC, MohitGupta121 requested changes

2023-07-05 13:41 UTC, MohitGupta121 commented on Drum-Sounds/.DS_Store
@Nayan808 Also remove this file from PR

2023-07-05 13:41 UTC, MohitGupta121 commented on Drum-Sounds/Readme.md
@Nayan808 why readme is empty?

2023-07-05 17:51 UTC, closed without merging