Add a Frontend Project - Playable Piano #2310
pranjay-poddar/Dev-Geeks pull request #2665
Opened 2023-06-25 10:47 UTC by Atulsingh30

# Title and Issue number 

Add a Frontend Project - Playable Piano #2310

Close #2310 
 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

2023-07-06 21:08 UTC, MohitGupta121 requested changes
@Atulsingh30 please remove the image from PR and upload it somewhere in cloud and use the link of the image to load the image into your Project.

2023-07-08 11:59 UTC, Atulsingh30 commented
I have changed the image, have a look. Tell me if any change is required @MohitGupta121

2023-07-10 17:21 UTC, MohitGupta121 requested changes
@

2023-07-10 17:21 UTC, MohitGupta121 commented on Frontend-Projects/Playable Piano/image.png
@Atulsingh30 no all images are still there `.wav`

2023-07-10 17:50 UTC, Atulsingh30 commented
Please check now! @MohitGupta121

2023-07-10 17:50 UTC, Atulsingh30 commented on Frontend-Projects/Playable Piano/image.png
Check now once if its correct

2023-07-11 17:21 UTC, merged