Mastermind Javascript game added - GSSOC'23
pranjay-poddar/Dev-Geeks pull request #2727
Opened 2023-06-27 13:35 UTC by srujana-16

# Mastermind game - new project 

Close #2414 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

2023-07-03 04:41 UTC, srujana-16 commented
Please merge this as part of GSSOC'23

2023-07-06 07:52 UTC, srujana-16 commented
Hello! Please check this PR and merge it as part of GSSOC'23

2023-07-06 20:45 UTC, MohitGupta121 requested changes
@srujana-16 also resolve conflicts

2023-07-06 20:45 UTC, MohitGupta121 commented on Js-Games/Mastemind/Screenshots/Mastermind.png
@srujana-16 please remove the image from PR and upload it somewhere in cloud and use the link of the image to load the image into your Project.

2023-07-07 11:03 UTC, srujana-16 commented
I have made the changes and resolved the conflicts, please check

2023-07-08 03:48 UTC, MohitGupta121 approved these changes

2023-07-08 03:48 UTC, MohitGupta121 requested changes
@srujana-16 still there are conflicts

2023-07-08 05:56 UTC, srujana-16 commented
Please check now

2023-07-08 22:11 UTC, MohitGupta121 approved these changes

2023-07-08 22:11 UTC, merged