Added Space Invaders Game
pranjay-poddar/Dev-Geeks pull request #2767
Opened 2023-06-28 18:47 UTC by Ayushkumargit7

# Title and Issue number 
Space Invaders Game

Issue #1251
Close #1251 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

2023-07-01 20:08 UTC, Ayushkumargit7 commented
@MohitGupta121 @pranjay-poddar  .Please Review and merge it.
Also Add the gssoc23 label and level label, if not added.

2023-07-01 20:27 UTC, MohitGupta121 requested changes

2023-07-01 20:27 UTC, MohitGupta121 commented on Js-Games/Space Invaders Game/aliens_image.png
@Ayushkumargit7 remove all those images from PR and use these images with the help of links. Upload image in anywhere and then use them in your Project. Thanks!

2023-07-02 10:46 UTC, Ayushkumargit7 commented on Js-Games/Space Invaders Game/aliens_image.png
@MohitGupta121 I added the images so that if in future images link change, then also it will be available.
I tried adding the images link by uploading , i uploaded on google drive , given public access then also it was not working.
I can make a images folder  ,and then commit the changes.Or tell what should i do.

2023-07-02 15:43 UTC, MohitGupta121 requested changes

2023-07-02 15:43 UTC, MohitGupta121 commented on Js-Games/Space Invaders Game/spaceship.png
No there is still the images in the PR.

2023-07-03 09:30 UTC, Ayushkumargit7 commented
@MohitGupta121 Removed the images and added the links , as you said.
Please add the gssoc23 label and appropriate level label .

2023-07-03 09:30 UTC, Ayushkumargit7 commented
@MohitGupta121 Removed the images and added the links , as you said.
Please add the gssoc23 label and appropriate level label .

2023-07-04 00:08 UTC, MohitGupta121 approved these changes

2023-07-04 00:08 UTC, merged