scroll-navbar-added
pranjay-poddar/Dev-Geeks pull request #2794
Opened 2023-06-29 17:06 UTC by rahulrana701

Scroll Navbar Project Under Navbar Section #2746

Close #2746

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

2023-06-29 17:06 UTC, rahulrana701 commented
hi @MohitGupta121 added the scroll-navbar project

2023-06-30 16:21 UTC, MohitGupta121 requested changes

2023-06-30 16:21 UTC, MohitGupta121 commented on Js-Projects/Giveaway
Why you adding this giveaway project in your PR. It's not part of this PR. Please remove this from here

2023-06-30 16:21 UTC, MohitGupta121 commented on Navbars/Scroll/tree-832079.jpg
Use image from Link not directly in your PR. Upload image somewhere and use it's link

2023-06-30 16:30 UTC, rahulrana701 commented
dont' know why it is happening I had pushed only scroll navbar project not this giveaway project .
But I will create a new pr for this as well

2023-06-30 17:14 UTC, closed without merging

2023-06-30 17:14 UTC, MohitGupta121 commented
Then I closing this PR create a new clean PR.