Apple clone is added
pranjay-poddar/Dev-Geeks pull request #2820
Opened 2023-06-30 16:53 UTC by shraddha761

# Title and Issue number 

Close #2231 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

2023-06-30 16:54 UTC, shraddha761 commented
@MohitGupta121 @pranjay-poddar please review

2023-06-30 17:18 UTC, MohitGupta121 requested changes
Same for all images.

2023-06-30 17:18 UTC, MohitGupta121 commented on Frontend-Projects/Apple-Clone/images/img1.jpeg
Remove images from PR and use them through link of images upload anywhere in cloud and fetch them.

2023-07-09 15:51 UTC, shraddha761 commented
@TusharKesarwani please review

2023-07-20 17:00 UTC, TusharKesarwani approved these changes

2023-07-20 17:01 UTC, TusharKesarwani commented on Frontend-Projects/Apple-Clone/images/img1.jpeg
I think images are of less size
So it wouldn't affect much

2023-08-06 05:24 UTC, closed without merging