Giveaway Project Added
pranjay-poddar/Dev-Geeks pull request #2827
Opened 2023-06-30 18:03 UTC by rahulrana701

Giveaway Project under JS projects #2620

Close #2620

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

2023-06-30 18:43 UTC, rahulrana701 commented
Hi @MohitGupta121 I have added the giveaway project now it will be working fine..

2023-07-01 03:08 UTC, MohitGupta121 requested changes

2023-07-01 03:08 UTC, MohitGupta121 commented on Js-Projects/Giveaway/img/pen-4337521.jpg
Remove image from PR, and if your project is using this use them from link firstly upload image somewhere and with link fetch it into your project.

2023-07-01 03:09 UTC, rahulrana701 commented
@MohitGupta121 ok

2023-07-02 16:44 UTC, closed without merging