Sample-Frontend-Project ADDED
pranjay-poddar/Dev-Geeks pull request #2844
Opened 2023-07-01 08:09 UTC by soubhik-111

# Title and Issue number 

I have added Sample -Frontend-Project under issue number #2408 

Close #2408 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

2023-07-01 08:15 UTC, soubhik-111 commented
@MohitGupta121 
Kindly merge it or give your feedback.

2023-07-01 19:58 UTC, MohitGupta121 requested changes
For all images otherwise this PR is good to merge

2023-07-01 19:58 UTC, MohitGupta121 commented on Frontend-Projects/Sample-Frontend-Project/images/contact.jpg
@soubhik-111 please remove all images from PR and use them through link in your project. Upload it somewhere in the cloud and fetch from there.

2023-07-01 20:02 UTC, soubhik-111 commented on Frontend-Projects/Sample-Frontend-Project/images/contact.jpg
@MohitGupta121 
Thanks for your valuable response 
May I know Why it is needed to upload in the cloud and then fetch rather than directly use it by adding them to a folder?

2023-07-01 20:17 UTC, MohitGupta121 commented on Frontend-Projects/Sample-Frontend-Project/images/contact.jpg
just upload the images anywhere but not in PR or the project then use that images link in the image_src index.html file because this will increase project size.

2023-07-01 20:19 UTC, soubhik-111 commented on Frontend-Projects/Sample-Frontend-Project/images/contact.jpg
Okay, That's good idea will do that

2023-07-01 21:54 UTC, soubhik-111 commented
@MohitGupta121 
Kindly Merge it

2023-07-02 15:28 UTC, MohitGupta121 approved these changes

2023-07-02 15:28 UTC, merged