Added ClockyClock to Js-Projects
pranjay-poddar/Dev-Geeks pull request #2847
Opened 2023-07-01 08:57 UTC by prernasngh

[GSSoC'23] Add a Clock Website(Analog Clock and Alarm Clock) #2208

Close #2208 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

2023-07-01 19:35 UTC, prernasngh commented
@pranjay-poddar @MohitGupta121 @Saurabh-kumar09 Sir, please review this PR made under GSSoC'23.

2023-07-01 19:46 UTC, MohitGupta121 requested changes

2023-07-01 19:46 UTC, MohitGupta121 commented on Js-Projects/ClockyClock/akram-huseyn-f3nGngsnp3A-unsplash.jpg
@prernasngh remove all images from PR and use them through link in your project. Upload it somewhere in the cloud and fetch from there.

2023-07-08 20:43 UTC, prernasngh commented
@pranjay-poddar @MohitGupta121 @Saurabh-kumar09  Sir, I have made the required changes. Can you please review the PR under GSSoC'23 ?

2023-07-09 17:18 UTC, MohitGupta121 requested changes

2023-07-09 17:18 UTC, MohitGupta121 commented on Js-Projects/ClockyClock/pexels-mikhail-nilov-6981406.mp4
@prernasngh please remove this video from PR, if that using in the project then upload it somewhere and then use that link to load the video

2023-07-09 19:36 UTC, prernasngh commented on Js-Projects/ClockyClock/pexels-mikhail-nilov-6981406.mp4
@MohitGupta121 Sir, I have removed the video from PR and added its link.

2023-07-11 07:22 UTC, prernasngh commented
@MohitGupta121 Sir, is the PR eligible to be merged ?

2023-07-12 20:36 UTC, MohitGupta121 approved these changes

2023-07-12 20:36 UTC, merged