#2854 New Login signup page
pranjay-poddar/Dev-Geeks pull request #2866
Opened 2023-07-01 13:54 UTC by PVBharadwaj

# Title and Issue number 
#2854  login page

Close #2854 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

2023-07-01 13:55 UTC, PVBharadwaj commented
@MohitGupta121  please review this PR under GSSoC'23

2023-07-01 19:47 UTC, MohitGupta121 requested changes

2023-07-01 19:47 UTC, MohitGupta121 commented on Frontend-Projects/new login signup page/assets/login.jpg
@PVBharadwaj  remove all images from PR and use them through link in your project. Upload it somewhere in the cloud and fetch from there.

2023-07-02 10:26 UTC, PVBharadwaj commented
@MohitGupta121  I have created a new PR #2910  by making the changes. Please review that PR and please close this one

2023-07-02 15:42 UTC, closed without merging