Added Encipher | Decipher
pranjay-poddar/Dev-Geeks pull request #2900
Opened 2023-07-02 07:20 UTC by siddarthdayala

# Title and Issue number 

Close #2817 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

2023-07-03 07:56 UTC, siddarthdayala commented
Hey @MohitGupta121 Could you please review this?

2023-07-04 00:07 UTC, MohitGupta121 requested changes
All images.

2023-07-04 00:07 UTC, MohitGupta121 commented on Frontend-Projects/Encipher | Decipher/rc.png
@siddarthdayala please do not upload this image in your PR, if your project is using an image upload it somewhere in the cloud and use that image link in your project. Thanks!

2023-07-23 17:10 UTC, siddarthdayala commented on Frontend-Projects/Encipher | Decipher/rc.png
hey @MohitGupta121  I resolved it. No images are used now

2023-07-25 16:47 UTC, MohitGupta121 requested changes

2023-07-25 16:47 UTC, MohitGupta121 commented on Frontend-Projects/Encipher | Decipher/cc.png
@siddarthdayala what you saying images are still there

2023-07-25 17:13 UTC, siddarthdayala commented on Frontend-Projects/Encipher | Decipher/cc.png
My PR shows some images but they are already deleted and nowhere associated with the website. I hope that it would not be a problem

2023-07-25 17:14 UTC, siddarthdayala commented on Frontend-Projects/Encipher | Decipher/cc.png
My file structure here might show the names of the images but they are not rendered as they were already deleted

2023-07-27 02:05 UTC, MohitGupta121 requested changes

2023-07-27 02:05 UTC, MohitGupta121 commented on Frontend-Projects/Encipher | Decipher/rc.png
you have to remove images from PR or make new clean PR

2023-07-27 02:06 UTC, closed without merging