Navbar added
pranjay-poddar/Dev-Geeks pull request #2930
Opened 2023-07-02 16:38 UTC by Shreyans2004

# Title and Issue number 

closes
Close #2925

I have added the navbar .Can it be merged now?
# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

2023-07-02 16:40 UTC, Shreyans2004 commented
@MohitGupta121 Can it be merged now?

2023-07-04 00:00 UTC, MohitGupta121 requested changes

2023-07-04 00:00 UTC, MohitGupta121 commented on Navbars/navbar_with_beautiful_background/image3.jpg
@Shreyans2004 please do not upload this image in your PR, if your project is using an image upload it somewhere in the cloud and use that image link in your project. Thanks!

2023-07-04 09:40 UTC, Shreyans2004 commented
@MohitGupta121  I have done the necessary changes. Can it be merged now?

2023-07-04 09:41 UTC, Shreyans2004 commented on Navbars/navbar_with_beautiful_background/image3.jpg
@MohitGupta121 I have done the necessary changes. Can it be merged now?

2023-07-04 14:14 UTC, MohitGupta121 approved these changes

2023-07-04 14:14 UTC, merged