Add files via upload
pranjay-poddar/Dev-Geeks pull request #2965
Opened 2023-07-03 13:35 UTC by Lakshya770

Added Space Impact (old Nokia Classic) game.

# Title and Issue number 

Title: Space Impact Game(old nokia classic)
Issue Number: #2763

Close: #2763

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

2023-07-07 15:29 UTC, Lakshya770 commented
@TusharKesarwani @pranjay-poddar @MohitGupta121 @Saurabh-kumar09 
Respected Sir,
Please review this PR and if everything feels good kindly merge it under GSSoC '23.

2023-07-08 03:54 UTC, MohitGupta121 requested changes
@Lakshya770  please remove all the images or gif from your PR and use them through cloud link. Upload somewhere the images and use them from that link.

2023-07-08 19:47 UTC, Lakshya770 commented
@TusharKesarwani @pranjay-poddar @MohitGupta121 @Saurabh-kumar09 
Respected Sir,
I have made all the requested changes in PR kindly review it .

2023-07-08 22:24 UTC, MohitGupta121 approved these changes

2023-07-08 22:24 UTC, merged