Added React based Project
pranjay-poddar/Dev-Geeks pull request #2990
Opened 2023-07-04 09:27 UTC by tayyab-ilyas

# Title and Issue number 

Added PomTasker a ReactJS based app

Close #2969 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

2023-07-04 09:29 UTC, tayyab-ilyas commented
hey @MohitGupta121 ! can you check this out? and also please don't forget to assign the Gssoc'23 label. Thanks!

2023-07-04 14:13 UTC, MohitGupta121 requested changes
@tayyab-ilyas PTAL

2023-07-04 14:13 UTC, MohitGupta121 commented on React-JS Projects/PomTasker/package-lock.json
Remove this package.lock from PR.

2023-07-04 14:13 UTC, MohitGupta121 commented on React-JS Projects/PomTasker/pomtasker.png
please remove all images from PR and upload it somewhere in cloud and use that images link in your project to load that through link.

2023-07-05 00:23 UTC, tayyab-ilyas commented on React-JS Projects/PomTasker/package-lock.json
Sorry it was silly of me to push this , have fixed it!

2023-07-05 00:25 UTC, tayyab-ilyas commented on React-JS Projects/PomTasker/pomtasker.png
I have removed the images instead added a live deployment link in the README.md.

2023-07-05 13:46 UTC, MohitGupta121 requested changes
@tayyab-ilyas you removed images but you also have to replace the images path with the image link from where image get load.

2023-07-05 13:46 UTC, MohitGupta121 commented on React-JS Projects/PomTasker/public/vite.svg
@tayyab-ilyas also remove this

2023-07-05 14:44 UTC, tayyab-ilyas commented on React-JS Projects/PomTasker/public/vite.svg
actually images were just part of the README.md, so I thought its better to remove the website screenshots and instead add the live deployment link.

2023-07-05 14:48 UTC, tayyab-ilyas commented on React-JS Projects/PomTasker/public/vite.svg
> @tayyab-ilyas also remove this

done.

2023-07-05 17:17 UTC, merged