[Add] "Keysmash", a keyboard game
pranjay-poddar/Dev-Geeks pull request #3058
Opened 2023-07-05 11:18 UTC by crapbagaah

# Keyboard game #2629 
I have added a keyboard game
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/90127903/dd07230d-0e3a-4f1c-9030-442fc62aa86c)

It is available both in dark and light mode, just clicking on the mode button at the top right corner changes its mode
![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/90127903/af3697d6-670d-4a45-8d2f-e858122253ec)

A keyboard game using html, css and javascript. On displaying the specific key, you need to click on it and it will move on to the next key. It is fun to play.

Please review the PR and add the levels under gssoc'23 as required. Thank you.

Close #2629 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

2023-07-07 16:31 UTC, crapbagaah commented
@MohitGupta121  @TusharKesarwani  @PoulavBhowmick03 please review the PR, thank you

2023-07-08 04:00 UTC, MohitGupta121 requested changes

2023-07-08 04:00 UTC, MohitGupta121 commented on Js-Games/Keyboard game/key.jpg
@crapbagaah  please remove all the images or gif from your PR and use them through cloud link. Upload somewhere the images and use them from that link.

2023-07-08 12:40 UTC, crapbagaah commented
@MohitGupta121 please review the PR now, I have made the necessary changes

2023-07-10 17:21 UTC, MohitGupta121 requested changes
@crapbagaah images are still present and zip file as well

2023-07-15 15:07 UTC, crapbagaah commented
@MohitGupta121 can you review the PR now, I made the necessary changes

2023-07-16 04:18 UTC, MohitGupta121 approved these changes

2023-07-16 04:18 UTC, merged