[ADD]: PING COMING SOON PAGE WITH MAIL VALIDATION ✨
pranjay-poddar/Dev-Geeks pull request #3085
Opened 2023-07-05 15:22 UTC by 0xabdulkhalid

# Close #3028 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

2023-07-05 17:14 UTC, MohitGupta121 requested changes

2023-07-05 17:14 UTC, MohitGupta121 commented on Frontend-Projects/Ping_Coming_Soon_Page/package-lock.json
remove this file from PR.

2023-07-06 00:18 UTC, 0xabdulkhalid commented
Now you can merge this @MohitGupta121.

2023-07-06 19:03 UTC, MohitGupta121 approved these changes

2023-07-06 19:03 UTC, merged