[GSSoC'23] : Add Pizza Delivery Website (Animated)
pranjay-poddar/Dev-Geeks pull request #3099
Opened 2023-07-05 19:39 UTC by Ash0807

# Title and Issue number 
This PR contains the code of frontend-Project "Pizza Delivery" Website : https://github.com/pranjay-poddar/Dev-Geeks/issues/2675
Close: https://github.com/pranjay-poddar/Dev-Geeks/issues/2675

# Demo

https://github.com/pranjay-poddar/Dev-Geeks/assets/93093775/c14b408d-b558-4651-8a45-5f7907545219

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

2023-07-05 19:44 UTC, Ash0807 commented
@MohitGupta121  @TusharKesarwani  @PoulavBhowmick03 
Please Review my PR

2023-07-06 19:02 UTC, MohitGupta121 requested changes
@Ash0807 please remove all the images from the PR and upload them somewhere in the cloud and use that images link in the image path to load image in your project

2023-07-08 18:03 UTC, Ash0807 commented
@MohitGupta121, I have made changes in my PR. If there is some more improvement, then inform me.

2023-07-08 22:26 UTC, MohitGupta121 approved these changes

2023-07-08 22:26 UTC, merged