Quiz Added
pranjay-poddar/Dev-Geeks pull request #3109
Opened 2023-07-06 03:38 UTC by Shreyans2004

# Title and Issue number 

Close #3035
I have added the customized Quiz. Can it be merged now?

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

2023-07-06 03:39 UTC, Shreyans2004 commented
@MohitGupta121 Can it be merged now?

2023-07-06 19:04 UTC, MohitGupta121 requested changes
@Shreyans2004 your project is Quiz then why you adding CountDown-Timer in your PR?

2023-07-07 04:20 UTC, Shreyans2004 commented
Sorry for the mistake.I have now deleted those files.The PR contains only the quiz part now.Can it be merged now?

2023-07-08 04:07 UTC, MohitGupta121 approved these changes

2023-07-08 04:07 UTC, merged