[gssoc23]: Btech Tea Shop: Scroll to top feature added
pranjay-poddar/Dev-Geeks pull request #3126
Opened 2023-07-06 11:45 UTC by invigorzz313

# Btech Tea Shop: scroll to top feature

Close #2790

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.

2023-07-06 12:28 UTC, invigorzz313 commented
@MohitGupta121 Kindly review this PR

2023-07-06 19:12 UTC, MohitGupta121 requested changes

2023-07-06 19:12 UTC, MohitGupta121 commented on Frontend-Projects/BTech Tea Shop/images/ToTop.png
@invigorzz313 please remove all the images from the PR and upload them somewhere in the cloud and use that images link in the image path to load image in your project

2023-07-07 06:39 UTC, invigorzz313 commented on Frontend-Projects/BTech Tea Shop/images/ToTop.png
@MohitGupta121  Removed image from the PR and made necessary changes.

2023-07-08 03:40 UTC, MohitGupta121 approved these changes

2023-07-08 03:40 UTC, merged