Random Color Generator
pranjay-poddar/Dev-Geeks pull request #3271
Opened 2023-07-08 18:43 UTC by Tusharjoshi1703

# Title and Issue number 

Close #2722 <issue_no>

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

2023-07-11 17:35 UTC, MohitGupta121 requested changes
@Tusharjoshi1703 I think this already present in the repo.

2023-07-11 17:40 UTC, Tusharjoshi1703 commented
@MohitGupta121 It is not present in the repo . Please have a look..

2023-07-12 20:24 UTC, MohitGupta121 approved these changes

2023-07-12 20:24 UTC, merged

2023-07-12 20:25 UTC, Tusharjoshi1703 commented
Thanks for merging it into main🙏👍

On Thu, 13 Jul, 2023, 01:54 MOHIT GUPTA, ***@***.***> wrote:

> Merged #3271 <https://github.com/pranjay-poddar/Dev-Geeks/pull/3271> into
> main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pranjay-poddar/Dev-Geeks/pull/3271#event-9803696422>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYZJSIWUHJT7BNAHLH6Y53TXP4BXPANCNFSM6AAAAAA2C742MM>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>