Clean vs Messy
pranjay-poddar/Dev-Geeks pull request #3327
Opened 2023-07-09 13:36 UTC by Shreyg-27

# Title and Issue number 
Clean vs Messy #2872 

Close #<issue_no>
Close #2872 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

2023-07-09 13:37 UTC, Shreyg-27 commented
Hi @MohitGupta121! I have completed this issue, kindly review it once.
Thank you.

2023-07-09 17:28 UTC, MohitGupta121 requested changes
@Shreyg-27 please remove all images from PR, upload them somewhere else like in GitHub or Drive then use that link in your project instead of the image path.

2023-07-09 19:17 UTC, Shreyg-27 commented
> @Shreyg-27 please remove all images from PR, upload them somewhere else like in GitHub or Drive then use that link in your project instead of the image path.

Hi @MohitGupta121! I have made the changes, removed all the images, and instead uploaded all the images in the drive, and provided the link for that as well. 
Thank you.

2023-07-11 17:05 UTC, MohitGupta121 approved these changes

2023-07-11 17:05 UTC, merged