added new project
pranjay-poddar/Dev-Geeks pull request #3359
Opened 2023-07-10 11:10 UTC by shineishukla

# Animated ToolTip #2963 

Close #2963 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

2023-07-10 11:11 UTC, shineishukla commented
@MohitGupta121  @pranjay-poddar @TusharKesarwani please review the pr and add GSSoC labels

2023-07-11 17:16 UTC, MohitGupta121 approved these changes

2023-07-11 17:17 UTC, MohitGupta121 requested changes
@shineishukla you have to move your project to a specific folder according to tech stack then it will merge - any of these [folders](https://github.com/pranjay-poddar/Dev-Geeks)

2023-07-12 03:21 UTC, shineishukla commented
@MohitGupta121 I have made the changes. Kindly review and add the labels.

2023-07-12 20:32 UTC, MohitGupta121 approved these changes

2023-07-12 20:32 UTC, merged