Frontend Project "To Do List" Box Background Improvement
pranjay-poddar/Dev-Geeks pull request #3401
Opened 2023-07-11 00:54 UTC by iamRabia-N

# Title and Issue number 
Frontend Project "To Do List" Box Background Improvement 
Close #3320

# Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`

2023-07-11 00:55 UTC, iamRabia-N commented
@MohitGupta121 Kindly review this PR.

2023-07-11 17:38 UTC, MohitGupta121 approved these changes

2023-07-11 17:39 UTC, MohitGupta121 requested changes
@iamRabia-N please resolved conflicts

2023-07-11 17:43 UTC, iamRabia-N commented
> @iamRabia-N please resolved conflicts

@MohitGupta121 Done with resolving conflict. You can review now.

2023-07-12 20:24 UTC, MohitGupta121 approved these changes

2023-07-12 20:24 UTC, merged