Frontend Project "TBT" Discover Exciting Destinations Section Styling
pranjay-poddar/Dev-Geeks pull request #3447
Opened 2023-07-11 19:30 UTC by iamRabia-N

# Title and Issue number 
Frontend Project "TBT" Discover Exciting Destinations Section Styling
Close #3411

# Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`

2023-07-11 19:31 UTC, iamRabia-N commented
@MohitGupta121 Kindly review this pr.

2023-07-12 20:32 UTC, MohitGupta121 requested changes
I approving your this small small PR's now next time please add your changes recording / Screenshots BEFORE and AFTER then I'll approve your PR. Thanks!

2023-07-13 08:54 UTC, iamRabia-N commented
@MohitGupta121

2023-07-14 01:48 UTC, MohitGupta121 approved these changes

2023-07-14 01:48 UTC, merged