Added a Gym-Landing Page
pranjay-poddar/Dev-Geeks pull request #3491
Opened 2023-07-13 04:39 UTC by AnkitaSikdar005

It is a Gym-Landing Page made using HTML and CSS. 
#3483 

Close #3483 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

![Gym-Landing-Page ](https://github.com/pranjay-poddar/Dev-Geeks/assets/115947852/3e31ad2f-fa8d-42e8-8f9f-fed3b3259732)

2023-07-13 07:25 UTC, AnkitaSikdar005 commented
@MohitGupta121  kindly please review this pull request.

2023-07-14 01:44 UTC, MohitGupta121 requested changes

2023-07-14 01:44 UTC, MohitGupta121 commented on Frontend-Projects/Gym-Landing Page/img/gym4.jpg
@AnkitaSikdar005 remove the images from PR and upload them somewhere else and use that link to load imgaes.

2023-07-14 10:56 UTC, AnkitaSikdar005 commented on Frontend-Projects/Gym-Landing Page/img/gym4.jpg
@MohitGupta121  The required changes have been done. Please ,kindly  review this pull request.

2023-07-16 04:45 UTC, MohitGupta121 approved these changes

2023-07-16 04:45 UTC, merged