Added Educational website
pranjay-poddar/Dev-Geeks pull request #3589
Opened 2023-07-14 18:19 UTC by PoulavBhowmick03

# Title and Issue number 
Landing page for an educational website #3481

Close #<issue_no>

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

![image](https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/57b2e309-a87b-4ab1-be05-dfacaed61776)

2023-07-14 18:20 UTC, PoulavBhowmick03 commented
@pranjay-poddar @MohitGupta121 Please merge this

2023-07-15 14:27 UTC, PoulavBhowmick03 commented
@pranjay-poddar @MohitGupta121 @TusharKesarwani

2023-07-16 04:22 UTC, MohitGupta121 requested changes

2023-07-16 04:22 UTC, MohitGupta121 commented on .vscode/settings.json
@PoulavBhowmick03 please don't change this.

2023-07-16 05:30 UTC, PoulavBhowmick03 commented
@MohitGupta121 fixed

2023-07-17 03:53 UTC, MohitGupta121 approved these changes

2023-07-17 03:53 UTC, merged