Added Cubula Javascript game
pranjay-poddar/Dev-Geeks pull request #3659
Opened 2023-07-15 16:30 UTC by jaivsh

# Added the Cubula game into Dev-Geeks 

I've completed the implementation of the cubula game. 

Close #3617 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

2023-07-15 16:30 UTC, jaivsh commented
Hi @MohitGupta121 @TusharKesarwani @pranjay-poddar please check this PR out! Thanks!

2023-07-16 04:17 UTC, MohitGupta121 requested changes
@jaivsh  please remove all images/gif from your PR and upload them somewhere else and then use that image/gif link to load in your project.

2023-07-16 07:34 UTC, jaivsh commented
Hi @MohitGupta121 I've did all the changes as proposed by you. Can you please check the PR again? Thanks

2023-07-17 03:56 UTC, MohitGupta121 approved these changes

2023-07-17 03:57 UTC, merged