Tour Company Website[GSSOC'23]
pranjay-poddar/Dev-Geeks pull request #3669
Opened 2023-07-15 20:20 UTC by apu52

# Title and Issue number 

**Tour Company Website**
Issue no. #3584 

Please take a review & merge it
 **Video**

https://github.com/pranjay-poddar/Dev-Geeks/assets/114172928/dc67c7a6-de46-41c2-844e-9acadf96b0cd

Close #3584 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

2023-07-15 20:24 UTC, apu52 commented
@MohitGupta121 @TusharKesarwani @pranjay-poddar please take a review & merge it under GSSOC

2023-07-16 04:16 UTC, MohitGupta121 requested changes
@apu52 please remove all images from your PR and upload them somewhere else and then use that image link to load in your project.

2023-07-16 05:42 UTC, apu52 commented
@MohitGupta121 I have removed the img file & already have used the img links in HTML from somewhere else. So can you please review & merge it?

2023-07-17 03:54 UTC, MohitGupta121 approved these changes

2023-07-17 03:54 UTC, merged