Frontend Project "PrimeFlix" Homepage Styling
pranjay-poddar/Dev-Geeks pull request #3702
Opened 2023-07-16 10:30 UTC by iamRabia-N

# Title and Issue number 
Frontend Project "PrimeFlix" Homepage Styling
Close #3642 

# Output

**Before**
![op (23)](https://github.com/pranjay-poddar/Dev-Geeks/assets/115794049/860c252c-9959-4a4b-8469-d5b5dd04ba4f)

**After**
![op (22)](https://github.com/pranjay-poddar/Dev-Geeks/assets/115794049/deda185a-574c-4a40-8cd2-58045f02cb36)

# Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`

2023-07-16 10:33 UTC, iamRabia-N commented
@MohitGupta121 Kindly review this pull request.

2023-07-17 07:34 UTC, iamRabia-N commented
@MohitGupta121

2023-07-18 05:03 UTC, MohitGupta121 requested changes
@iamRabia-N please resolves conflicts

2023-07-20 16:41 UTC, MohitGupta121 approved these changes

2023-07-20 16:41 UTC, merged