[Gssoc'23] Added Bangalore House Price Prediction | Machine Learning Projects #3138
pranjay-poddar/Dev-Geeks pull request #3943
Opened 2023-07-21 09:07 UTC by kanishkasah20

# Bangalore-House-Price-Prediction ISSUENO. #3138 

I have succesfully deployed this machine learning project [Bangalore-House-Price-Prediction] using streamlit website .
 PR 1692648138155229d347c216070549f77f1bea5f

Close #3138 

Screenshot of model:
<img width="722" alt="image" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/114860158/0d6404f3-b4a2-4264-aad8-e1582d72c167">

With model accuracy:0.86
<img width="466" alt="image" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/114860158/df4885fb-dabd-43c1-a47e-86d12b5ceb65">

# Checklist:

- [Yes] I have mentioned the issue number in my Pull Request.
- [Yes] I have commented my code, particularly in hard-to-understand areas
- [Yes] I have created a helpful and easy to understand `README.md`

2023-07-21 09:08 UTC, kanishkasah20 commented
Please review it @MohitGupta121 sir

2023-07-21 18:48 UTC, MohitGupta121 requested changes
@kanishkasah20 remove .idea folder

2023-07-21 19:20 UTC, kanishkasah20 commented
Done, idea folder (deleted) 
please review it again @MohitGupta121

2023-07-22 22:57 UTC, MohitGupta121 approved these changes

2023-07-22 22:57 UTC, merged