Music player Frontend Project 3344
pranjay-poddar/Dev-Geeks pull request #4113
Opened 2023-07-24 08:05 UTC by soubhik-111

# Title and Issue number 

Music player Frontend Project #3344 

Close #3344 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

2023-07-24 08:06 UTC, soubhik-111 commented
@MohitGupta121 
Kindly merge it or give your feedback.

2023-07-24 09:59 UTC, soubhik-111 commented
Kindly add GSSOC'23 tag

2023-07-27 02:14 UTC, MohitGupta121 requested changes

2023-07-27 02:14 UTC, MohitGupta121 commented on Frontend-Projects/Music_Player/favicon.png
@soubhik-111 remove the image image from PR and upload somewhere else and use image link to load into your project.

2023-07-27 17:03 UTC, closed without merging

2023-07-27 17:03 UTC, soubhik-111 commented on Frontend-Projects/Music_Player/favicon.png
Okay, I will create a new PR.