app landing page is added
pranjay-poddar/Dev-Geeks pull request #4130
Opened 2023-07-24 15:20 UTC by Sushilverma002

# Title and Issue number 

Close #3972 

https://github.com/pranjay-poddar/Dev-Geeks/assets/114687502/88492634-cf39-459e-88e3-962b2a9f14e5

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

2023-07-24 15:21 UTC, Sushilverma002 commented
@MohitGupta121 and @TusharKesarwani have a look!!!!!!!!!!!

2023-07-25 16:59 UTC, MohitGupta121 requested changes
@Sushilverma002 please do not upload this image in your PR, if your project is using an image upload it somewhere in the cloud and use that image link in your project. Thanks!

2023-07-26 08:01 UTC, Sushilverma002 commented
@MohitGupta121 done issue is resolved now u can merge this PR . and also i have added the readme file so it helps others.

2023-07-27 02:18 UTC, MohitGupta121 approved these changes

2023-07-27 02:18 UTC, merged