Feedback1
pranjay-poddar/Dev-Geeks pull request #4141
Opened 2023-07-24 16:13 UTC by Shreyans2004

# Title and Issue number 

I have added the project. Can it be merged now?

Close #4123

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

2023-07-24 16:14 UTC, Shreyans2004 commented
@MohitGupta121 ,@TusharKesarwani Can it be merged now?

2023-07-25 16:59 UTC, MohitGupta121 requested changes
@Shreyans2004 please add only 1 project remove website-calculate project if this project is related to feedback-page

2023-07-25 17:14 UTC, Shreyans2004 commented
Sorry for the inconvinience, I have completed the necessary changes.
@MohitGupta121 ,@TusharKesarwani  Can it be merged now?

2023-07-27 02:06 UTC, MohitGupta121 approved these changes

2023-07-27 02:06 UTC, merged