[GSSoC'23]: Add QR Code Generator Web Page
pranjay-poddar/Dev-Geeks pull request #4211
Opened 2023-07-25 20:51 UTC by Ash0807

# Title and Issue number 
This PR contains the code of frontend-Project "QR Code Generator" Web Page :  https://github.com/pranjay-poddar/Dev-Geeks/issues/3867
Close: https://github.com/pranjay-poddar/Dev-Geeks/issues/3867

# Demo Screenshot 
This screen shot shows if you choose any URL or text then it can be easily converted into a QR code format and can be easily scan with the help of scanner, like 'Google lens'.

![254707372-d568f944-078c-4a92-b64e-76c8f3c0d31c](https://github.com/pranjay-poddar/Dev-Geeks/assets/93093775/f6ad6511-efa1-4dbf-b590-c8c70d44f226)

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md

2023-07-29 18:37 UTC, Ash0807 commented
@MohitGupta121 and @Ijaiswalshivam Please review my pull request and merge it with the label "ready to merge"

2023-07-31 06:00 UTC, MohitGupta121 requested changes

2023-08-01 19:33 UTC, Ash0807 commented on Frontend-Projects/ash.gif
@MohitGupta121, now Please check my pull request and merge it with the label "ready to merge". If still any changes required then inform me soon.

2023-08-02 21:34 UTC, Ash0807 commented on Frontend-Projects/ash.gif
I have already do that

2023-08-04 17:39 UTC, MohitGupta121 approved these changes

2023-08-04 17:39 UTC, merged