expense tracker app running issue fixed
pranjay-poddar/Dev-Geeks pull request #4307
Opened 2023-07-27 12:28 UTC by aritroo

# Title and Issue number 
Expense Tracker

Close #4143 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [x] I have fixed the file structure and the app not running issue
- [x] I have added addtional features and the UI is improved

2023-07-27 12:29 UTC, aritroo commented
Hello @MohitGupta121 , Sir please review my PR and also add a label for gssoc'23

2023-07-29 12:36 UTC, MohitGupta121 requested changes
Remove this

2023-07-29 12:37 UTC, MohitGupta121 requested changes

2023-07-29 12:37 UTC, MohitGupta121 commented on Flutter Projects/.DS_Store
Remove this also

2023-07-29 13:11 UTC, aritroo commented
can't able to make changes and I am closing this PR and I will make the desired changes in new PR.

2023-07-29 13:11 UTC, closed without merging