[GSSoc'23] Added University website | Frontend Project #4078
pranjay-poddar/Dev-Geeks pull request #4324
Opened 2023-07-27 16:59 UTC by kanishkasah20

# University website ISSUENO. #4078 

Added a responsive university website which consists of different webpages such as HOME, ABOUT, BLOG, COURSE etc using html, css, js, php and deployed it on netlify app. PR d4d75a2eb89061a14eeabf07aee8928de21b34ea

Website link:- https://64c0e6e4b92a5745217d14d1--iridescent-crostata-d2142e.netlify.app/index.html

Close #4078 

Screenshot of website:-
-main page
<img width="883" alt="image" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/114860158/136ab9a0-269c-4bc5-add3-4a2a394240b2">

-blog page
<img width="868" alt="image" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/114860158/efe36c54-f1fe-4a0b-aeeb-1b7cf5ff39d5">

-Course page:
<img width="899" alt="image" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/114860158/3d19c30b-83a9-4ed3-ad26-a7ed6f58c991">

# Checklist:

- [Yes] I have mentioned the issue number in my Pull Request.
- [Yes] I have commented my code, particularly in hard-to-understand areas
- [Yes] I have created a helpful and easy to understand `README.md`

2023-07-30 21:03 UTC, kanishkasah20 commented
Please review this pr @TusharKesarwani @MohitGupta121

2023-07-31 06:01 UTC, MohitGupta121 requested changes
@kanishkasah20 Remove all the image from PR and upload it somewhere and then use it link in your project to load the image.

2023-07-31 09:32 UTC, kanishkasah20 commented
Please  review it again @MohitGupta121  , added the link of images https://github.com/pranjay-poddar/Dev-Geeks/pull/4324/commits/81aed8961e7061649f3d753c19d8f77972f0f36b

2023-08-01 16:19 UTC, MohitGupta121 approved these changes

2023-08-01 16:19 UTC, merged