Added pride flags collection Javascript
pranjay-poddar/Dev-Geeks pull request #4444
Opened 2023-07-31 02:18 UTC by jaivsh

# Added historical pride flags collection project in javascript 

I've added the pride flags project, which contains more than 30 pride flags belonging to various "pride" genders and communities around the world. All of these are created and designed in CSS.

<img width="1470" alt="Screenshot 2023-07-31 at 7 45 23 AM" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/93859359/c2fdbc5c-51b9-4ff5-945c-0db99dbe8f7e">

Close #4262 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

2023-07-31 02:19 UTC, jaivsh commented
@pranjay-poddar @TusharKesarwani @MohitGupta121 please see this PR

2023-07-31 05:57 UTC, MohitGupta121 requested changes
@jaivsh resolves conflicts

2023-07-31 06:30 UTC, jaivsh commented
@MohitGupta121 @TusharKesarwani fixed conflicts, please see

2023-08-01 16:29 UTC, MohitGupta121 approved these changes

2023-08-01 16:29 UTC, merged