Cpp project
pranjay-poddar/Dev-Geeks pull request #4492
Opened 2023-07-31 11:44 UTC by shineishukla

# Rock, Paper, scissors (C++) #4241

Close #4241 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

2023-08-03 05:42 UTC, shineishukla commented
@TusharKesarwani @MohitGupta121 kindly review the pr.

2023-08-04 06:51 UTC, TusharKesarwani requested changes
Remove .vscode folder

2023-08-04 08:37 UTC, shineishukla commented
> Remove .vscode folder

Made the changes.

2023-08-05 08:16 UTC, TusharKesarwani approved these changes

2023-08-05 08:16 UTC, merged