Images re-linked to the site [cars company]
pranjay-poddar/Dev-Geeks pull request #4685
Opened 2023-08-03 11:18 UTC by SnigdhaP2022

# Car company images linked

Close #4501 

# Checklist:

- [✅] I have mentioned the issue number in my Pull Request.
- [✅] I have commented my code, particularly in hard-to-understand areas

# Before
<img width="1440" alt="Screenshot 2023-08-03 at 4 47 37 PM" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/102572480/0d6ab3c4-d8de-43c6-b122-72315cac5b5f">

# After
<img width="1440" alt="Screenshot 2023-08-03 at 4 45 22 PM" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/102572480/92a44fea-fdf9-440c-a7fd-0294e1bd1757">

2023-08-03 11:26 UTC, SnigdhaP2022 commented
@TusharKesarwani  Kindly, review this

2023-08-05 02:34 UTC, SnigdhaP2022 commented
@MohitGupta121 @TusharKesarwani Kindly, review this

2023-08-06 04:56 UTC, MohitGupta121 requested changes

2023-08-06 04:56 UTC, MohitGupta121 commented on Frontend-Projects/car company website/images/cars.jpeg
@SnigdhaP2022 remove this image from PR and use it as a link after uploading somewhere else.

2023-08-06 05:27 UTC, SnigdhaP2022 commented on Frontend-Projects/car company website/images/cars.jpeg
@MohitGupta121 issue has been resolved. Kindly, review it

2023-08-07 04:19 UTC, MohitGupta121 approved these changes

2023-08-07 04:19 UTC, merged