[chess game] section styling
pranjay-poddar/Dev-Geeks pull request #4686
Opened 2023-08-03 11:38 UTC by SnigdhaP2022

# Chess game Background styling

Close #4502 

# Checklist:

- [✅] I have mentioned the issue number in my Pull Request.
- [✅] I have commented my code, particularly in hard-to-understand areas

# Before
<img width="1440" alt="Screenshot 2023-08-03 at 5 03 11 PM" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/102572480/8f2f35be-bc86-4ce1-9724-efe4eb5fb60f">

# After
<img width="1440" alt="Screenshot 2023-08-03 at 5 03 29 PM" src="https://github.com/pranjay-poddar/Dev-Geeks/assets/102572480/57f39ab4-5f52-47fc-9a44-e43a1c225ec5">

2023-08-03 11:45 UTC, SnigdhaP2022 commented
@TusharKesarwani  Kindly,review this

2023-08-05 02:34 UTC, SnigdhaP2022 commented
@MohitGupta121 @TusharKesarwani Kindly, review this

2023-08-06 04:56 UTC, MohitGupta121 requested changes

2023-08-06 04:56 UTC, MohitGupta121 commented on Frontend-Projects/Chess Website/chess.jpeg
@SnigdhaP2022 remove this image from PR and use it as a link after uploading somewhere else.

2023-08-06 05:33 UTC, SnigdhaP2022 commented on Frontend-Projects/Chess Website/chess.jpeg
@MohitGupta121 Issue resolved. Kindly, review and merge this PR

2023-08-07 04:16 UTC, MohitGupta121 approved these changes

2023-08-07 04:16 UTC, merged