Medical Education Website
pranjay-poddar/Dev-Geeks pull request #4697
Opened 2023-08-03 15:05 UTC by Sreenija03

# Title and Issue number 

Added a new Medical education website

Close #4608 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

2023-08-03 15:06 UTC, Sreenija03 commented
@MohitGupta121 @TusharKesarwani Can you please review this PR

2023-08-04 17:59 UTC, MohitGupta121 requested changes
@Sreenija03 please upload only 1 project in your PR there are currently multiple project here.

2023-08-05 02:54 UTC, Sreenija03 commented
@MohitGupta121 I have made the change .Can you please check now

2023-08-07 03:41 UTC, MohitGupta121 approved these changes

2023-08-07 03:41 UTC, merged