TABLE BOOKING FEATURE
pranjay-poddar/Dev-Geeks pull request #4862
Opened 2023-08-06 07:29 UTC by kanishka-parmar

Table booking feature  ISSUE NO:-1365 

Close #1365

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

2023-08-06 16:53 UTC, kanishka-parmar commented
@pranjay-poddar 
Kindly review this pull request.

2023-08-08 20:25 UTC, MohitGupta121 requested changes
@kanishka-parmar please remove all images from PR and upload them somewhere else and then load them through link in your project

2023-08-09 14:49 UTC, kanishka-parmar commented
@MohitGupta121 
I have made the changes as said you can review it .

2023-08-09 21:11 UTC, MohitGupta121 approved these changes

2023-08-09 21:11 UTC, merged