Real time chat web using Reactjs, socket.io  #482
pranjay-poddar/Dev-Geeks pull request #546
Opened 2022-10-03 18:37 UTC by iamsid0908

# Title and Issue number 
Real-time chat web using Reactjs, socket.io 

issue no.  #<482>

# Checklist:

- [] I have mentioned the issue number in my Pull Request.
- [x] I have commented on my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy-to-understand `README.md`

2022-10-03 18:39 UTC, iamsid0908 commented
hey, @pranjay-poddar  please review my PR.

2022-10-03 19:56 UTC, pranjay-poddar requested changes
mention the issue number correctly, for eg #123 (remove the brackets<>)

2022-10-04 06:53 UTC, iamsid0908 commented
@pranjay-poddar  done. pls, review it. and merge it.

2022-10-04 07:20 UTC, pranjay-poddar approved these changes

2022-10-04 07:20 UTC, merged