added Hospital Management System in C
pranjay-poddar/Dev-Geeks pull request #548
Opened 2022-10-03 18:40 UTC by dishankkumaryadav

# Title and Issue number 

Close #<issue_no>

# Checklist:

- [] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

2022-10-03 20:00 UTC, pranjay-poddar approved these changes

2022-10-03 20:01 UTC, pranjay-poddar requested changes
mention the issue number in PR template and fill the checklist

2022-10-03 20:20 UTC, pranjay-poddar commented
First raise an issue and get it assigned under hacktoberfest'22

2023-06-21 03:27 UTC, MohitGupta121 commented
Closing as part of Hacktoberfest 2021 and now outdated.

2023-06-21 03:27 UTC, closed without merging