Sneaker ecommerce website #689
pranjay-poddar/Dev-Geeks pull request #700
Opened 2022-10-08 08:10 UTC by Vidhanjain143

Sneaker ecommerce website #689

Added frontend  code for frontend.

Close #<689>

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

2022-10-08 08:57 UTC, pranjay-poddar requested changes
remove node modules folder or put it in .gitignore

2022-10-08 11:49 UTC, Vidhanjain143 commented
Removed that folder

2022-10-08 19:29 UTC, pranjay-poddar approved these changes

2022-10-08 19:29 UTC, merged

2022-10-11 13:46 UTC, Vidhanjain143 commented
why it got excluded .